sudo: required
services:
    - docker

script:
    - docker build -t adistiffler/travis .
    - docker tag adistiffler/travis adistiffler/travis:3.0 
    - docker images adistiffler/travis:3.0

before_deploy:
    - docker login -u <username> -p <password>

deploy:
    provider: script
    script: docker push adistiffler/travis
    on:
        branch: master
