sudo: required
services:
    - docker

script:
    - docker build -t adistiffler/travis .
    - docker tag adistiffler/travis adistiffler/travis:1.0 
    - docker images adistiffler/travis:1.0

before_deploy:
    - docker login -u adistiffler -p Babu@1987

deploy:
    provider: script
    script: docker push adistiffler/travis
    on:
        branch: master
